#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Verifica se há alterações staged
if git diff --cached --quiet; then
  echo "Nenhuma alteração para commit"
  exit 0
fi

# Executa Prettier apenas nos arquivos staged
npm run prettier
